Update 7.x-2.x README for REST API and associated links.
MarketoMA/marketo_ma pull request #18
Opened 2016-11-04 10:51 UTC by mccrodp

As mentioned in https://github.com/MarketoMA/marketo_ma/issues/13

2016-11-04 12:39 UTC, jyokum requested changes

2016-11-04 12:39 UTC, jyokum commented on README.md
>  **Marketo Fields**
Field management has changed and needs to be reflected in docs.

2016-11-04 12:43 UTC, mccrodp commented on README.md
>  **Marketo Fields**
👍 Will add now

2016-11-04 12:55 UTC, mccrodp commented on README.md
>  **Marketo Fields**
Done. Please review @jyokum!

2016-11-04 20:27 UTC, jyokum requested changes

2016-11-04 20:27 UTC, jyokum commented on README.md
>  **Marketo Fields**
This section is no longer relevant and can be remove entirely.

2016-11-05 09:11 UTC, mccrodp commented on README.md
>  **Marketo Fields**
Thanks @jyokum, missed that. Committed now.

2016-11-05 14:06 UTC, merged