Issue #2610556 by Jaesin, jyokum, RoloDMonkey: D8 version docs?
MarketoMA/marketo_ma pull request #3
Opened 2016-09-21 19:37 UTC by Jaesin

Updates the docs to reflect there isn't currently support for the webform module. Also includes the attribution commit message.

2016-09-21 20:00 UTC, RoloDMonkey commented on modules/marketo_ma_contact/src/Form/MarketoMaContactConfiguration.php
> +      '#title' => $this->t('Capture Data'),
Is it clear that this is capturing data for Marketo?

2016-09-23 02:33 UTC, Jaesin commented on modules/marketo_ma_contact/src/Form/MarketoMaContactConfiguration.php
> +      '#title' => $this->t('Capture Data'),
"Capture Data" is the terminology that was used in the documentation. Did we move away from this terminology for a reason. I think the description could be better for sure:

> This needs to be checked in order to enable data capture for this contact form.

2016-09-23 12:02 UTC, jyokum commented on modules/marketo_ma_contact/src/Form/MarketoMaContactConfiguration.php
> +      '#title' => $this->t('Capture Data'),
"Capture Data" is what is used on the Webform integration but the description indicates the connection to Marketo so at a minimum we should do something similar here.

Current Webform description = "If checked, captured form information will be sent to Marketo"

2016-09-23 15:29 UTC, RoloDMonkey commented on modules/marketo_ma_contact/src/Form/MarketoMaContactConfiguration.php
> +      '#title' => $this->t('Capture Data'),
Is there an issue for this on drupal.org?

2016-09-23 16:50 UTC, Jaesin commented on modules/marketo_ma_contact/src/Form/MarketoMaContactConfiguration.php
> +      '#title' => $this->t('Capture Data'),
I updated it to what the webform module used. Could have also gone with `Unless checked, captured form information will not be sent to Marketo.` No d.o. issue.

2016-09-23 18:23 UTC, RoloDMonkey commented
I have created an issue for this: https://www.drupal.org/node/2805417

@jyokum: Do you have any comments?

2016-09-24 11:53 UTC, jyokum requested changes
A number of additional updates should be made to get README.md into better shape.
- Installation step 2 still refers to SOAP.
- Tracking Method section still refers to SOAP.
- SOAP API section needs to be replaced with REST details.

2016-09-28 13:01 UTC, RoloDMonkey commented
@Jaesin, @jyokum: Are either one of you working on the changes suggested on Saturday? If not, I have some time.

2016-09-28 17:59 UTC, Jaesin commented
Thanks @RoloDMonkey I'm a bit busy with some client work this week.

2016-10-05 18:54 UTC, Jaesin commented
I'm going to work on this now.

2016-10-05 20:05 UTC, RoloDMonkey commented
Thanks! I got caught up in some other stuff. Let me know immediately if you need anything.

2016-10-18 00:01 UTC, merged